# Generated by Django 2.1.7 on 2019-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='source',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='From',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='To',
            field=models.CharField(default='', max_length=100),
        ),
    ]
